version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    open-pull-requests-limit: 50
  - package-ecosystem: "npm"
    directory: "/ids-webconsole/src/main/angular/"
    schedule:
      interval: "daily"
    target-branch: "master"
    open-pull-requests-limit: 50
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "master"
    open-pull-requests-limit: 50
